### ISSUE TITLE
Revision version 1 of example.vsd from @msunderwd

### ISSUE THREAD

**Issue by klk32003** [JMRI/vsdecoder#1]
The extension `rev1` means `revision version 1`. 
I don't know if all works under Linux or macOS.  My system is Windows.

Profile `GE 7FDL` now comes with Start and Shutdown sounds from `EMD 645 Turbo`. 
Reason was an audio format issue. Pardon, if this is painful for your ears. My goal was not sound optimizing, but just a good working VSD file.

Klaus Killinger

[example_rev1.zip](https://github.com/JMRI/vsdecoder/files/753203/example_rev1.zip)

**Comment by bobjacobsen** [comment]
I don't know much about the Sound Decoder.  Can we call this something more evocative, like perhaps "GE_7FDL" or "EMD 645 Turbo"?  Or does it contain more than one type?

**Comment by klk32003** [comment]
> I don't know much about the Sound Decoder.

Let me take the chance to reference to @msunderwd http://www.jmri.org/help/en/manual/DecoderPro/Main_VSD.shtml and to https://sourceforge.net/p/searchlight2/wiki4/VSD_File_Definition/.


>  Can we call this something more evocative, like perhaps "GE_7FDL" or "EMD 645 Turbo"? Or does it contain more than one type?

Yes, this VSD file comes with four Profiles (locomotives): `EMD 645 Turbo`, `GE 7FDL`, `EMD NW2` and `Generic Steam`. Some of the WAV files are re-used in other Profiles. This might be an advantage when having variants of a particular type of locomotive. 

But I could separate `example_rev1.vsd` into four VSD files with loco based names.

**Comment by klk32003** [comment]
Files uploaded as .zip and renamed as .vsd (I hope that works).
I like the idea to have one loco type in a .vsd file.

When I download a VSD file from here, the name of the file changes form .vsd to .zip.
I was curious and loaded a ZIP file into VSDecoder. And that works as well as a file with extension .vsd. 

[Generic_Steam.vsd](https://github.com/JMRI/vsdecoder/files/764551/Generic_Steam.vsd)
[EMD_645_Turbo.vsd](https://github.com/JMRI/vsdecoder/files/764560/EMD_645_Turbo.vsd)
[EMD_NW2.vsd](https://github.com/JMRI/vsdecoder/files/764572/EMD_NW2.vsd)
[GE_7FDL.vsd](https://github.com/JMRI/vsdecoder/files/764577/GE_7FDL.vsd)
[Class64.vsd](https://github.com/JMRI/vsdecoder/files/766442/Class64.vsd)    Note: Class64.vsd needs JMRI 4.7.1 or higher

**Comment by bobjacobsen** [comment]
I've merged those five files in via #2.  @klk32003, could you make sure I didn't damage them?  Thanks!

**Comment by msunderwd** [comment]
Looks like they all transferred OK.

I've got some bugs to work out in the code, apparently, but that doesn't appear to have anything to do with these changes.

**Comment by klk32003** [comment]
I also can confirm that all works well. Thank you!

**Comment by msunderwd** [comment]
Oh, and for the record, a VSD file *is* just a ZIP file with the extension changed.  I made sure the loader could handle either extension (or, IIRC any filename) as long as the file format itself is a valid ZIP file.

The VSD format allows for either single profile per file, or multiple profiles per file, depending on the user or creator's preference... and you guessed correctly that re-use of source audio is allowed in order to allow for variants of similar engines... makes for less file size, too!

**Comment by klk32003** [comment]
>  I made sure the loader could handle either extension (or, IIRC any filename) ...

 That's right. I can even omit the file extension or rename the file name - all works fine.
